# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Meteorologie hautnah
subtitle: Hochschulwettbewerb 2022
#repository: "MeteorologieHautnah/MeteorologieHautnah"
logo: /assets/images/logo.jpg
email: meteorologie.hautnah@uni-leipzig.de
description: >- # this means to ignore newlines until "baseurl:"
  Webseite für das Citizen Science Projekt "Meteorologie hautnah" des Instituts für Meteorologie der Universität Leipzig.

baseurl: "/MeteorologieHautnah" # the subpath of your site, e.g. /blog
#url: "https://meteorologiehautnah.github.io/MeteorologieHautnah/" # the base hostname & protocol for your site, e.g. http://example.com
locale: "de"
timezone: "Europe/Berlin" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
twitter_username: MeteoHautnah
github_username:  MeteorologieHautnah
search: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/MeteoHautnah"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MeteorologieHautnah/MeteorologieHautnah"

# Build settings
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-email-protect
  - jekyll-paginate
  - jekyll-gist
  - jekyll-redirect-from

#comments:
#  provider: "utterances"

paginate: 5 # amount of posts to show
paginate_path: /_posts/page:num

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      author_profile: true
      read_time: true
      comments: true
      share: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
        layout: single
        author_profile: true
        comments: false

atom_feed:
  hide: true

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
